#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Commit message must not be empty"
    exit 1
fi

# CONVENTIAL COMMIT SCOPES
texts=("[FIX]" "[FEAT]" "[DELETE]")
q
# STRING FOR VALIDATE
input=$commit_message

valid=false

for text in "${texts[@]}"; do
    if [[ "$input" == *"$text"* ]]; then
        valid=true
        break
    fi
done

# Imprimir el resultado de la validación
if [ "$valid" = true ]; then
    echo "El string es válido."
    exit 0
else
    echo -e "Please write commit with a scope by example: \n"
    echo " [FEAT] must be used when a commit adds a new feature in the repository."
    echo " [FIX] must be used when a commit represents a bug fix in the repository."
    echo " [DELETE] must be used when a commit represents a deletion of code in the repository."
    exit 1
fi
